api_controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  prefix: /api/v1
  name_prefix: api_

home:
  path: /
  controller: App\Controller\DefaultController::index

react_frontend:
  path: /{reactRouting}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'base.html.twig'
  requirements:
    reactRouting: '.+'
