# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\API\Nasa\:
    resource: '../src/API/Nasa/*'
    public: false
    bind:
      $nasaApiKey: '%env(NASA_API_KEY)%'

  api.nasa.client:
    class: GuzzleHttp\Client
    arguments:
      - { base_uri: 'https://api.nasa.gov/' }

  api.nasa.pesquisa.client:
    class: GuzzleHttp\Client
    arguments:
      - { base_uri: 'https://images-api.nasa.gov/' }

  GuzzleHttp\Client:
    alias: 'api.nasa.client'

  App\Infra\NasaApiClient:
    arguments:
      $clientGuzzle: '@api.nasa.client'
      $nasaApiKey: '%env(NASA_API_KEY)%'

  App\Infra\NasaPesquisaApiClient:
    arguments:
      $clientGuzzle: '@api.nasa.pesquisa.client'

  App\API\PesquisaAPI:
    arguments:
      $clientGuzzle: '@api.nasa.pesquisa.client'
      $tradutor: '@App\API\TradutorAPI'

  api.tradutor.client:
    class: Stichoza\GoogleTranslate\GoogleTranslate
    calls:
      - setTarget: ['pt']
      - setSource: ['en']

  App\API\TradutorAPI:
    arguments:
      $tradutor: '@api.tradutor.client'
